"""
﻿【中华正统】 八字/四柱/大运 → 【双库并联】 ╔══════════════════════════════════════════════════════╗ ║ Step 1: 排盘 — lunar_python ║ ║ ┌─ Solar.fromYmdHms(year,month,day,hour,minute,0)║ ║ └─ → getLunar().getEightChar() → 四柱干支 ║ ╚══════════════════════════════════════════════════════╝ ↓ ╔══════════════════════════════════════════════════════╗ ║ Step 2: 骨架 — lunar_python ║ ║ ┌─ Solar.toFullString() → 公历信息+星座 ║ ║ ├─ Lunar.toFullString() → 农历+纳音+星宿+ ║ ║ │ 彭祖百忌+喜贵财神方位 ║ ║ ├─ Lunar.getJieQiTable() → 24节气精确日期 ║ ║ ├─ EightChar → 四柱/纳音/五行/藏干 ║ ║ │ /十神/旬空/身宫 ║ ║ └─ EightChar.getYun(1) → 大运起岁+十步+流年 ║ ╚══════════════════════════════════════════════════════╝ ↓ ╔══════════════════════════════════════════════════════╗ ║ Step 3: 血肉 — bazi_china ║ ║ ⚠️ 先 sys.path.insert(0, 'app/src/main/python') ║ ║ ⚠️ datas.nayins 的key是tuple; datas.ganzhi60 的key是int 1-60║ ║ 正确: datas.nayins[('戊','寅')] → '城头土' ║ ║ 错误: datas.nayins['戊寅'] → KeyError ║ ║ ⚠️ datas.empties key也是tuple! ║ ║ 正确: datas.empties[('甲','子')] → ('戌','亥')║ ║ ⚠️ datas.tiaohous 是简码需解码: ║ ║ '1丙2_甲' = 第一用神丙, 第二用神甲 ║ ║ '1壬2丙甲' = 第一用神壬, 第二用神丙甲 ║ ║ ⚠️ shengxiao.output(des,zhi,key) 三参调用 ║ ║ ║ ║ ┌─ sizi.summarys['戊日壬子'] → 时柱古诀 ║ ║ ├─ datas.day_shens['将星']['午'] → 日支神煞 ║ ║ ├─ datas.year_shens['孤辰']['寅'] → 年支神煞 ║ ║ ├─ datas.month_shens['天德']['子'] → 月支神煞 ║ ║ ├─ datas.g_shens['天乙']['戊'] → 天乙贵人 ║ ║ ├─ datas.minggongs['丑'] → 命宫断语 ║ ║ ├─ datas.rizhus['戊午'] → 日主断语 ║ ║ ├─ datas.jinbuhuan['戊午'] → 金不换调候+大运喜忌║ ║ ├─ datas.lu_types['戊'][('戊','巳')] → 禄类型 ║ ║ ├─ datas.self_zuo['印'] → 自坐解释 ║ ║ ├─ yue.months['甲子'] → 月令详细论述 ║ ║ ├─ ganzhi.gan_hes → 天干五合详解 ║ ║ ├─ ganzhi.zhi_6hes/3hes/chongs/haies/poes/xings ║ ║ ├─ ganzhi.gan_desc/zhi_desc → 干支特性 ║ ║ ├─ ganzhi.zhi_zangs → 地支藏干(脏腑对应) ║ ║ └─ ganzhi.ten_deities['戊']['子'] → 十二宫状态 ║ ╚══════════════════════════════════════════════════════╝ 【关键坑位提醒】 • datas.nayins[('戊','寅')] → '城头土' (查纳音, key是tuple) • datas.ganzhi60[1] → '甲子' (60甲子序列表, key是int 1-60) • datas.empties key也是tuple: ('甲','子') • datas.tiaohous 是简码: '1丙2_甲' 格式 1=第一用神, 2=第二用神, _=分隔符 • shengxiao.output(des, zhi, key) 三参调用 • lunar_python.Yun.getDaYun() 返回的是list, 需遍历 • lunar_python的流年/流月: dy.getLiuNian(year)[0].getGanZhi() (getLiuNian返回list, 取[0]为干支) 【分工总结】 lunar_python = 排盘骨架 + 大运流年 + 农历信息 → 先跑, 不可替代 bazi_china = 神煞断语 + 调候用神 + 古诀解盘 + 干支关係库 + 禄/十二宫 + 流月论述 → 后跑, 不可省略 生日（含时辰）

【农历/干支/天文】 农历/黄历/择日 → cnlunar(Python) ← lunar_python, Lunar(JS引擎) 日期即可 公历农历转换/八字 → lunar_python(Python) ← Lunar(JS引擎,可离线算Solar/Lunar/EightChar/DaYun/JieQi) 日期即可 二十八宿/宿曜 → Lunar.getTwentyEightMans() ← cnlunar 日期/生日均可 建除十二神/黄道黑道 → cnlunar ← lunar_python 日期即可 吉神凶神/彭祖百忌 → cnlunar 日期即可 值年太岁/本命太岁 → cnlunar/lunar_python ← 日期即可 生肖/干支/合婚/神煞 → bazi_china ← lunar_python 生日可选 bazi_china 是纯 Python 静态库(无pip,源码在app/src/main/python/bazi_china/)。调法: import sys; sys.path.insert(0, 'app/src/main/python') from bazi_china import ganzhi, datas, shengxiao, sizi, yue ganzhi.Gan[:10] → ['甲','乙','丙','丁','戊','己','庚','辛','壬','癸'] ganzhi.Zhi[:12] → ['子','丑','寅','卯','辰','巳','午','未','申','酉','戌','亥'] datas.shengxiaos[zhi] → 该地支的生肖名 (如datas.shengxiaos['子']→'鼠') shengxiao.output(des,zhi,key)→ 打印生肖合/冲/刑/害关系 (shengxiao.py CLI) 生肖合婚/配对查询 → 单独调用 shengxiao.output，不需要先排八字 用户问\"属X和什么合/冲\"时调，入参: zhi=生肖对应地支(鼠→子 牛→丑…), key=合/六/会/冲/刑/害/破 例: shengxiao.output('', '子', '合') → '猴龙' (子与申猴辰龙三合) shengxiao.output('', '子', '冲') → '马' (子午冲) 【luohou — 择日/风水/罗猴/九宫飞星】 它能做什么: luohou.yearly_nine_stars(year) → 年九宫飞星: 返回JiuFeiXing对象, 用属性名取方位 jfx.东 .南 .西 .北 .中 .东北 .东南 .西南 .西北 luohou.monthly_nine_stars(年支) → 月九星: 返回{月份:星名} luohou.daily_nine_stars(lunar对象) → 日九星 luohou.get_hou(d, xiazhi, dongzhi) → 每日择日(三参都是datetime.date) luohou.get_jizhu(年干,年支) → 太岁压祭主 luohou.jiuxings_dsp → 九星吉凶说明文字 什么时候调它: "今天日子怎么样"/"搬家/动土/嫁娶/开工选日子" → from datetime import date; from bazi_china import luohou; from lunar_python import Lunar → table=Lunar.fromYmd(2024,1,1).getJieQiTable() → xz=date(table['夏至'].getYear(),table['夏至'].getMonth(),table['夏至'].getDay()) → dz=date(table['DONG_ZHI'].getYear(),table['DONG_ZHI'].getMonth(),table['DONG_ZHI'].getDay()) → luohou.get_hou(date(2024,6,21), xz, dz) # 直接print输出 "今年什么方位吉利"/"财位在哪"/"病符在哪" → jfx=luohou.yearly_nine_stars(2024); jfx.东 / jfx.南 / jfx.西 / jfx.北 / jfx.中 / jfx.东北 / jfx.东南 / jfx.西南 / jfx.西北 "这个月飞星到哪" → luohou.monthly_nine_stars('子') "能动土吗/能开工吗" → luohou.get_jizhu(年干,年支) + get_hou()查岁破 sizi.summarys → 120项四柱解盘字典 (ai自己探索sizi.summarys.keys()查看可用键) yue.months[月柱] → 流月详解 (键为月柱干支如'甲寅', 从lunar_python EightChar.getMonth()取值) 神煞/纳音/空亡/命宫/日主/调候/建禄: datas.day_shens/month_shens/year_shens/g_shens/nayins/empties/minggongs/rizhus/jinbuhuan/jianlus 天干地支/藏干十神/干支关系: ganzhi.gan_desc/zhi_desc/ten_deities/gan_hes/zhi_6hes/zhi_3hes/zhi_chongs/zhi_xings/zhi_haies/zhi_poes 注: bazi_china 里只有 bazi.py(2549行)是CLI工具, 其余模块(ganzhi/datas/sizi/yue/shengxiao/luohou)全是库函数可以直接 import 调 节气和天文 → lunar_python ← cnlunar 日期即可

【JS引擎调用】
Lunar (JS)  → eval_javascript(library='lunar-engine', code='Lunar.Solar.fromDate(new Date(2026,5,19)) 又 Lunar.Lunar.fromDate(d) 又 Lunar.EightChar.fromLunar(lunar) 又 Lunar.DaYun(...) 又 Lunar.JieQi.getJieQi(2026)

【注意事项】
cnlunar.Lunar() 构造必须传 datetime 对象（含hour），不能只传 date。
正确: cnlunar.Lunar(datetime(2026,6,25,12,0,0))
错误: cnlunar.Lunar(date(2026,6,25)) → 报错 'date' object has no attribute 'hour'
"""
